services:
  alseraj-security-website:
    image: ghcr.io/xsabaa5/alseraj-security-iq:latest
    container_name: alseraj-security-website
    restart: unless-stopped
    networks:
      - traefik-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1/ || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alseraj-security-website-http.rule=Host(`security.alseraj.iq`)"
      - "traefik.http.routers.alseraj-security-website-http.entrypoints=web"
      - "traefik.http.routers.alseraj-security-website-http.middlewares=redirect-web-to-websecure@internal"
      - "traefik.http.routers.alseraj-security-website.rule=Host(`security.alseraj.iq`)"
      - "traefik.http.routers.alseraj-security-website.entrypoints=websecure"
      - "traefik.http.routers.alseraj-security-website.tls.certresolver=letsencrypt"
      - "traefik.http.services.alseraj-security-website.loadbalancer.server.port=80"

networks:
  traefik-network:
    external: true
